# Generated by Django 5.1.15 on 2026-02-16 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/')),
                ('results_json', models.JSONField(default=list)),
                ('num_detections', models.IntegerField(default=0)),
                ('max_confidence', models.FloatField(default=0.0)),
                ('processing_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'detection_result',
                'ordering': ['-created_at'],
            },
        ),
    ]
