# Generated by Django 5.1.15 on 2026-02-16 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='discoveries/%Y/%m/%d/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='discoveries/annotated/%Y/%m/%d/')),
                ('clover_type', models.CharField(choices=[('three-leaf', '3-Leaf Clover'), ('four-leaf', '4-Leaf Clover'), ('five-leaf', '5-Leaf Clover'), ('six-plus-leaf', '6+ Leaf Clover')], max_length=20)),
                ('confidence', models.FloatField()),
                ('bbox_json', models.JSONField(default=dict)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'discoveries',
                'db_table': 'discovery',
                'ordering': ['-created_at'],
            },
        ),
    ]
